src/Entity/Product.php
<?php

namespace App\Entity;

use App\Repository\ProductRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ProductRepository::class)]
class Product
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column(nullable: true)]
    private ?float $purchasePrice = null;

    #[ORM\Column]
    private ?float $price = null;

    #[ORM\Column(nullable: true)]
    private ?int $promo = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $createdAt = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $updatedAt = null;

    #[ORM\Column(nullable: true)]
    private ?bool $isPublished = null;

    #[ORM\ManyToOne(inversedBy: 'products')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Shop $shop = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $productImage = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $productDescription = null;

    #[ORM\Column(nullable: true)]
    private ?int $quantityStocke = null;

    /**
     * @var Collection<int, OrderDetailles>
     */
    #[ORM\OneToMany(targetEntity: OrderDetailles::class, mappedBy: 'product', orphanRemoval: true)]
    private Collection $orderDetailles;

    /**
     * @var Collection<int, Categories>
     */
    #[ORM\ManyToMany(targetEntity: Categories::class, inversedBy: 'products')]
    private Collection $category;

    #[ORM\Column(nullable: true)]
    private ?float $promoPrice = null;

    #[ORM\Column(nullable: true)]
    private ?int $quantitySales = null;

    public function __construct()
    {
        $this->orderDetailles = new ArrayCollection();
        $this->category = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getPurchasePrice(): ?float
    {
        return $this->purchasePrice;
    }

    public function setPurchasePrice(?float $purchasePrice): static
    {
        $this->purchasePrice = $purchasePrice;

        return $this;
    }

    public function getPrice(): ?float
    {
        return $this->price;
    }

    public function setPrice(float $price): static
    {
        $this->price = $price;

        return $this;
    }

    public function getPromo(): ?int
    {
        return $this->promo;
    }

    public function setPromo(?int $promo): static
    {
        $this->promo = $promo;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->createdAt ?? new \DateTimeImmutable();
    }

    public function setCreatedAt(\DateTimeImmutable $createdAt): static
    {
        $this->createdAt = new \DateTimeImmutable();

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updatedAt ?? new \DateTimeImmutable();
    }

    public function setUpdatedAt(\DateTimeImmutable $updatedAt): static
    {
        $this->updatedAt =  new \DateTimeImmutable();

        return $this;
    }

    public function isPublished(): ?bool
    {
        return $this->isPublished;
    }

    public function setPublished(?bool $isPublished): static
    {
        $this->isPublished = $isPublished;

        return $this;
    }

    public function getShop(): ?Shop
    {
        return $this->shop;
    }

    public function setShop(?Shop $shop): static
    {
        $this->shop = $shop;

        return $this;
    }

    public function getProductImage(): ?string
    {
        return $this->productImage;
    }

    public function setProductImage(string $productImage): static
    {
        $this->productImage = $productImage;

        return $this;
    }

    public function getProductDescription(): ?string
    {
        return $this->productDescription;
    }

    public function setProductDescription(?string $productDescription): static
    {
        $this->productDescription = $productDescription;

        return $this;
    }

    public function getQuantityStocke(): ?int
    {
        return $this->quantityStocke;
    }

    public function setQuantityStocke(?int $quantityStocke): static
    {
        $this->quantityStocke = $quantityStocke;

        return $this;
    }

    /**
     * @return Collection<int, OrderDetailles>
     */
    public function getOrderDetailles(): Collection
    {
        return $this->orderDetailles;
    }

    public function addOrderDetaille(OrderDetailles $orderDetaille): static
    {
        if (!$this->orderDetailles->contains($orderDetaille)) {
            $this->orderDetailles->add($orderDetaille);
            $orderDetaille->setProduct($this);
        }

        return $this;
    }

    public function removeOrderDetaille(OrderDetailles $orderDetaille): static
    {
        if ($this->orderDetailles->removeElement($orderDetaille)) {
            // set the owning side to null (unless already changed)
            if ($orderDetaille->getProduct() === $this) {
                $orderDetaille->setProduct(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Categories>
     */
    public function getCategory(): Collection
    {
        return $this->category;
    }

    public function addCategory(Categories $category): static
    {
        if (!$this->category->contains($category)) {
            $this->category->add($category);
        }

        return $this;
    }

    public function removeCategory(Categories $category): static
    {
        $this->category->removeElement($category);

        return $this;
    }

    public function getPromoPrice(): ?float
    {
        return $this->promoPrice;
    }

    public function setPromoPrice(?float $promoPrice): static
    {
        $this->promoPrice = $promoPrice;

        return $this;
    }

    public function getQuantitySales(): ?int
    {
        return $this->quantitySales;
    }

    public function setQuantitySales(?int $quantitySales): static
    {
        $this->quantitySales = $quantitySales;

        return $this;
    }
}

templates/card/_product.html.twig
{% for product in products %}
  {% if product.published == true and product.quantityStocke > 0 %}
    <article class="relative flex flex-col overflow-hidden rounded-lg border">
      <div class="aspect-square overflow-hidden p-2">
        <a href="{{ path('product.show', { id: product.id }) }}"><img class="h-full w-full object-cover transition-all duration-300 group-hover:scale-125" src="{{ asset('images/uploads/products/' ~ product.productImage) }}" alt="Product image" /></a>
      </div>
      {% if product.promo > 0 %}
        <div class="absolute top-0 m-2 rounded-full bg-white">
          <p class="rounded-full bg-skyblue-800 p-1 text-sm font-bold tracking-wide text-white sm:py-1 sm:px-3">- {{ product.promo }}%</p>
        </div>
      {% endif %}
      <div class="mb-4 mx-auto flex w-10/12 flex-col items-start justify-between gap-1">
        <div class="flex">
          <p class="mr-3 text-sm font-semibold">{{ product.promo > 0 ? product.PromoPrice|format_currency('XOF', locale='fr') : product.price|format_currency('XOF', locale='fr') }}</p>
          <del class="text-xs text-gray-400">{{ product.promo > 0 ? product.price|format_currency('XOF', locale='fr') : '' }}</del>
        </div>
        <h3 class="text-sm text-gray-600 truncate">{{ product.name }}</h3>
        {% for category in product.category %}
          <span class="text-sm font-light text-gray-500">#{{ category.name }}</span>
        {% endfor %}
      </div>
      <button type="button" id="{{ product.id }}" class="group mx-auto add-to-cart mb-2 flex h-10 w-10/12 items-stretch overflow-hidden rounded-md text-gray-600">
        <div class="flex w-full items-center justify-center bg-purple-700 text-white text-xs uppercase transition group-hover:bg-purple-600 group-hover:text-white">Acheter</div>
        <div class="flex items-center justify-center bg-purple-600 text-white px-5 transition group-hover:bg-purple-700 group-hover:text-white">
          <svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" class="bi h-5 w-5 bi-cart-plus" viewBox="0 0 16 16">
            <path d="M9 5.5a.5.5 0 0 0-1 0V7H6.5a.5.5 0 0 0 0 1H8v1.5a.5.5 0 0 0 1 0V8h1.5a.5.5 0 0 0 0-1H9z" />
            <path d="M.5 1a.5.5 0 0 0 0 1h1.11l.401 1.607 1.498 7.985A.5.5 0 0 0 4 12h1a2 2 0 1 0 0 4 2 2 0 0 0 0-4h7a2 2 0 1 0 0 4 2 2 0 0 0 0-4h1a.5.5 0 0 0 .491-.408l1.5-8A.5.5 0 0 0 14.5 3H2.89l-.405-1.621A.5.5 0 0 0 2 1zm3.915 10L3.102 4h10.796l-1.313 7zM6 14a1 1 0 1 1-2 0 1 1 0 0 1 2 0m7 0a1 1 0 1 1-2 0 1 1 0 0 1 2 0" />
          </svg>
        </div>
      </button>
    </article>
  {% endif %}
{% endfor %}