src/Entity/Shop.php
<?php

namespace App\Entity;

use App\Repository\ShopRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ShopRepository::class)]
class Shop
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $comName = null;

    #[ORM\OneToOne(inversedBy: 'shop', cascade: ['persist', 'remove'])]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $owner = null;

    #[ORM\Column(length: 255)]
    private ?string $adress = null;

    /**
     * @var Collection<int, Customer>
     */
    #[ORM\OneToMany(targetEntity: Customer::class, mappedBy: 'shop', orphanRemoval: true, cascade: ['persist', 'remove'])]
    private Collection $customers;

    /**
     * @var Collection<int, Collecte>
     */
    #[ORM\OneToMany(targetEntity: Collecte::class, mappedBy: 'shop', orphanRemoval: true, cascade: ['persist', 'remove'])]
    private Collection $collectes;

    #[ORM\Column]
    private ?\DateTimeImmutable $updatedAt = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $createdAt = null;

    /**
     * @var Collection<int, Employe>
     */
    #[ORM\OneToMany(targetEntity: Employe::class, mappedBy: 'shop', cascade: ['persist', 'remove'])]
    private Collection $employes;

    /**
     * @var Collection<int, Product>
     */
    #[ORM\OneToMany(targetEntity: Product::class, mappedBy: 'shop', orphanRemoval: true)]
    private Collection $products;

    /**
     * @var Collection<int, Order>
     */
    #[ORM\OneToMany(targetEntity: Order::class, mappedBy: 'shop')]
    private Collection $orders;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $PhoneNumber = null;

    /**
     * @var Collection<int, Shipe>
     */
    #[ORM\OneToMany(targetEntity: Shipe::class, mappedBy: 'shop')]
    private Collection $shipes;

    /**
     * @var Collection<int, Invoice>
     */
    #[ORM\OneToMany(targetEntity: Invoice::class, mappedBy: 'shop', orphanRemoval: true)]
    private Collection $invoices;

    public function __construct()
    {
        $this->customers = new ArrayCollection();
        $this->collectes = new ArrayCollection();
        $this->employes = new ArrayCollection();
        $this->products = new ArrayCollection();
        $this->orders = new ArrayCollection();
        $this->shipes = new ArrayCollection();
        $this->invoices = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getComName(): ?string
    {
        return $this->comName;
    }

    public function setComName(string $comName): static
    {
        $this->comName = $comName;

        return $this;
    }

    public function getOwner(): ?User
    {
        return $this->owner;
    }

    public function setOwner(User $owner): static
    {
        $this->owner = $owner;

        return $this;
    }

    public function getAdress(): ?string
    {
        return $this->adress;
    }

    public function setAdress(string $adress): static
    {
        $this->adress = $adress;

        return $this;
    }

    /**
     * @return Collection<int, Customer>
     */
    public function getCustomers(): Collection
    {
        return $this->customers;
    }

    public function addCustomer(Customer $customer): static
    {
        if (!$this->customers->contains($customer)) {
            $this->customers->add($customer);
            $customer->setShop($this);
        }

        return $this;
    }

    public function removeCustomer(Customer $customer): static
    {
        if ($this->customers->removeElement($customer)) {
            // set the owning side to null (unless already changed)
            if ($customer->getShop() === $this) {
                $customer->setShop(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Collecte>
     */
    public function getCollectes(): Collection
    {
        return $this->collectes;
    }

    public function addCollecte(Collecte $collecte): static
    {
        if (!$this->collectes->contains($collecte)) {
            $this->collectes->add($collecte);
            $collecte->setShop($this);
        }

        return $this;
    }

    public function removeCollecte(Collecte $collecte): static
    {
        if ($this->collectes->removeElement($collecte)) {
            // set the owning side to null (unless already changed)
            if ($collecte->getShop() === $this) {
                $collecte->setShop(null);
            }
        }

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(\DateTimeImmutable $updatedAt): static
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeImmutable $createdAt): static
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    /**
     * @return Collection<int, Employe>
     */
    public function getEmployes(): Collection
    {
        return $this->employes;
    }

    public function addEmploye(Employe $employe): static
    {
        if (!$this->employes->contains($employe)) {
            $this->employes->add($employe);
            $employe->setShop($this);
        }

        return $this;
    }

    public function removeEmploye(Employe $employe): static
    {
        if ($this->employes->removeElement($employe)) {
            // set the owning side to null (unless already changed)
            if ($employe->getShop() === $this) {
                $employe->setShop(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Product>
     */
    public function getProducts(): Collection
    {
        return $this->products;
    }

    public function addProduct(Product $product): static
    {
        if (!$this->products->contains($product)) {
            $this->products->add($product);
            $product->setShop($this);
        }

        return $this;
    }

    public function removeProduct(Product $product): static
    {
        if ($this->products->removeElement($product)) {
            // set the owning side to null (unless already changed)
            if ($product->getShop() === $this) {
                $product->setShop(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Order>
     */
    public function getOrders(): Collection
    {
        return $this->orders;
    }

    public function addOrder(Order $order): static
    {
        if (!$this->orders->contains($order)) {
            $this->orders->add($order);
            $order->setShop($this);
        }

        return $this;
    }

    public function removeOrder(Order $order): static
    {
        if ($this->orders->removeElement($order)) {
            // set the owning side to null (unless already changed)
            if ($order->getShop() === $this) {
                $order->setShop(null);
            }
        }

        return $this;
    }

    public function getPhoneNumber(): ?string
    {
        return $this->PhoneNumber;
    }

    public function setPhoneNumber(?string $PhoneNumber): static
    {
        $this->PhoneNumber = $PhoneNumber;

        return $this;
    }

    /**
     * @return Collection<int, Shipe>
     */
    public function getShipes(): Collection
    {
        return $this->shipes;
    }

    public function addShipe(Shipe $shipe): static
    {
        if (!$this->shipes->contains($shipe)) {
            $this->shipes->add($shipe);
            $shipe->setShop($this);
        }

        return $this;
    }

    public function removeShipe(Shipe $shipe): static
    {
        if ($this->shipes->removeElement($shipe)) {
            // set the owning side to null (unless already changed)
            if ($shipe->getShop() === $this) {
                $shipe->setShop(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Invoice>
     */
    public function getInvoices(): Collection
    {
        return $this->invoices;
    }

    public function addInvoice(Invoice $invoice): static
    {
        if (!$this->invoices->contains($invoice)) {
            $this->invoices->add($invoice);
            $invoice->setShop($this);
        }

        return $this;
    }

    public function removeInvoice(Invoice $invoice): static
    {
        if ($this->invoices->removeElement($invoice)) {
            // set the owning side to null (unless already changed)
            if ($invoice->getShop() === $this) {
                $invoice->setShop(null);
            }
        }

        return $this;
    }
}

src/Form/CollecteType.php
<?php

namespace App\Form;

use App\Entity\Collecte;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CollecteType extends AbstractType
{
  public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder->add('collecteDetailles', CollectionType::class, [
                'entry_type' => CollecteDetailsType::class,
                'allow_add' => true,
                'allow_delete' => true,
                'by_reference' => false,
                'label' => 'Ajouter les vêtements à laver',
                'entry_options' => [ 
                    'label' => false 
                ],
                'attr' => [
                    'class' => 'my-4',
                    'data-controller' => 'form-collection',
                    'data-form-collection-form-type-value' => 'addable',
                    'data-form-collection-add-label-value' => 'Ajouter un vêtement',
                    'data-form-collection-delete-label-value' => '<svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" fill="currentColor" viewBox="0 0 448 512"><!--!Font Awesome Free 6.5.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2024 Fonticons, Inc.--><path d="M135.2 17.7C140.6 6.8 151.7 0 163.8 0H284.2c12.1 0 23.2 6.8 28.6 17.7L320 32h96c17.7 0 32 14.3 32 32s-14.3 32-32 32H32C14.3 96 0 81.7 0 64S14.3 32 32 32h96l7.2-14.3zM32 128H416V448c0 35.3-28.7 64-64 64H96c-35.3 0-64-28.7-64-64V128zm96 64c-8.8 0-16 7.2-16 16V432c0 8.8 7.2 16 16 16s16-7.2 16-16V208c0-8.8-7.2-16-16-16zm96 0c-8.8 0-16 7.2-16 16V432c0 8.8 7.2 16 16 16s16-7.2 16-16V208c0-8.8-7.2-16-16-16zm96 0c-8.8 0-16 7.2-16 16V432c0 8.8 7.2 16 16 16s16-7.2 16-16V208c0-8.8-7.2-16-16-16z"/></svg>',
                ],
            ])
        ;
    }

    public static function typeCollecte(string $type = null): string
    {
        return $type;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Collecte::class,
        ]);
    }
}

templates/collecte/_customerForm.html.twig
<div class="flex flex-col max-w-sm my-3 px-4 mx-auto">
  {% if customer != null %}
    {% if app.user %}
      <div class="flex flex-col gap-4 p-2 text-sm">
        <p>Le client à dejas utilisé la plateforme.</p>
      </div>
    {% endif %}
    {{ form_row(form.customer, { row_class: 'mb-2', label_class: 'block text-sm font-medium leading-6 text-gray-900', error_item_class: 'text-red-500 text-sm font-medium', widget_class: 'block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-purple-600 sm:text-sm sm:leading-6', widget_disabled_class: 'my disabled widget classes', widget_errors_class: 'ring-1 ring-inset ring-orange-600' }) }}
  {% else %}
    {{ form_row(form.phoneNumber, { row_class: 'mb-2', label_class: 'block text-sm font-medium leading-6 text-gray-900', error_item_class: 'text-red-500 text-sm font-medium', widget_class: 'block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-purple-600 sm:text-sm sm:leading-6', widget_disabled_class: 'my disabled widget classes', widget_errors_class: 'ring-1 ring-inset ring-orange-600' }) }}
    {{ form_row(form.fullName, { row_class: 'mb-2', label_class: 'block text-sm font-medium leading-6 text-gray-900', error_item_class: 'text-red-500 text-sm font-medium', widget_class: 'block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-purple-600 sm:text-sm sm:leading-6', widget_disabled_class: 'my disabled widget classes', widget_errors_class: 'ring-1 ring-inset ring-orange-600' }) }}
    {{ form_row(form.adress, { row_class: 'mb-2', label_class: 'block text-sm font-medium leading-6 text-gray-900', error_item_class: 'text-red-500 text-sm font-medium', widget_class: 'block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-purple-600 sm:text-sm sm:leading-6', widget_disabled_class: 'my disabled widget classes', widget_errors_class: 'ring-1 ring-inset ring-orange-600' }) }}
    <div class="flex flex-col gap-4 p-2">
      <p class="text-sm font-medium text-purple-950" id="localisation-message">Veuillez autoriser la localisation afin que notre équipe puisse vous trouver plus facilement.</p>
      <div class="flex gap-2">
        {{ form_row(form.coordLng, { row_class: 'flex-2', label_class: 'block text-sm font-medium leading-6 text-gray-900', error_item_class: 'text-red-500 text-sm font-medium', widget_class: 'block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-purple-600 sm:text-sm sm:leading-6', widget_disabled_class: 'my disabled widget classes', widget_errors_class: 'ring-1 ring-inset ring-orange-600', attr: { disabled: true } }) }}
        {{ form_row(form.coordLat, { row_class: 'flex-2', label_class: 'block text-sm font-medium leading-6 text-gray-900', error_item_class: 'text-red-500 text-sm font-medium', widget_class: 'block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-purple-600 sm:text-sm sm:leading-6', widget_disabled_class: 'my disabled widget classes', widget_errors_class: 'ring-1 ring-inset ring-orange-600', attr: { disabled: true } }) }}
        <button type="button" id="localise" class="flex-1 inline-flex items-center justify-center px-3 py-1 text-base font-medium text-center text-white rounded-lg bg-yellow-600 hover:bg-yellow-700 focus:ring-4 focus:ring-yellow-300 dark:focus:ring-yellow-900">
          <svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" class="w-7 h-7" viewBox="0 0 384 512">
            <!-- !Font Awesome Free 6.5.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2024 Fonticons, Inc. -->
            <path d="M215.7 499.2C267 435 384 279.4 384 192C384 86 298 0 192 0S0 86 0 192c0 87.4 117 243 168.3 307.2c12.3 15.3 35.1 15.3 47.4 0zM192 128a64 64 0 1 1 0 128 64 64 0 1 1 0-128z" />
          </svg>
        </button>
      </div>
    </div>
  {% endif %}
  <div class="flex justify-end gap-4 px-4">
    <a href="{{ path('home') }}" class="inline-flex items-center justify-center px-3 py-1.5 text-base font-medium border text-center text-purple-700 rounded-lg bg-gray-100 hover:bg-gray-200 focus:ring-4 focus:ring-gray-300 dark:focus:ring-gray-400">Retour</a>
    {% if app.user %}
      <button class="inline-flex items-center justify-center px-3 py-1.5 text-base font-medium text-center text-white rounded-lg bg-purple-600 hover:bg-purple-700 focus:ring-4 focus:ring-purple-300 dark:focus:ring-purple-900">{{ button_label|default('Save') }}</button>
    {% else %}
      <button class="inline-flex items-center justify-center px-3 py-1.5 text-base font-medium text-center text-white rounded-lg bg-purple-600 hover:bg-purple-700 focus:ring-4 focus:ring-purple-300 dark:focus:ring-purple-900">Suivant</button>
    {% endif %}
  </div>
</div>

templates/collecte/_delete_form.html.twig
<form method="post" action="{{ path('collecte.delete', {'id': collecte.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ collecte.id) }}">
    <button class="btn">Delete</button>
</form>

templates/collecte/_recap.html.twig
{% if app.user %}
  <div class="flex justify-between lg:p-5">
    <div class="text-sm">
      <h2>Client</h2>
      <div class="text-left">
        <span class="text-semibold text-purple-950">Nom &amp; prénom :</span>
        <span>{{ collecte.customer.fullName }}</span>
      </div>
      <div class="text-left">
        <span class="text-semibold text-purple-950">Téléfone :</span>
        <span>{{ collecte.customer.phoneNumber }}</span>
      </div>
      <div class="text-left">
        <span class="text-semibold text-purple-950">Adresse :</span>
        <span>{{ collecte.customer.adress }}</span>
      </div>
    </div>
    <div class="text-sm">
      <h2>Collecte</h2>
      <div class="text-left">
        <span class="text-semibold text-purple-950">Pressing :</span>
        <span class="text-semibold font-extralight">{{ collecte.shop.comName }}</span>
      </div>
      <div class="text-left">
        <span class="text-semibold text-purple-950">Téléfone :</span>
        <span class="">{{ collecte.shop.owner.telefone }}</span>
      </div>
      <div class="text-left">
        <span class="text-semibold text-purple-950">Adresse :</span>
        <span>{{ collecte.shop.adress }}</span>
      </div>
      <div class="text-left">
        <span class="text-semibold text-purple-950">Date :</span>
        <span>{{ collecte.collectedAt|format_datetime(locale='fr') }}</span>
      </div>
    </div>
    <div class="text-sm">
      {% if qrCode %}
        <img src="{{ qrCode }}" alt="Qr code" width="150" height="150" />
        <a href="{{ qrCode }}" download>Telecharger</a>
      {% endif %}
    </div>
  </div>
{% else %}
  <div class="text-sm font-medium text-purple-950 p-4">
    <p>L'aperçus de votre prochaine facture, notre collecteur le confirmeras avec vous.</p>
  </div>
{% endif %}
<div class="mt-5 shadow-sm border rounded-lg overflow-x-auto">
  {% if collectePea == 'clothingPea' %}
    <table class="w-full sm:w-full table-auto text-sm text-left">
      <thead class="bg-gray-50 text-purple-950 w-80 font-medium border-b">
        <tr>
          <th class="py-2 px-4">Pois du collecte</th>
          <th class="py-2 px-4">Palier de prix</th>
          <th class="py-2 px-4"></th>
        </tr>
      </thead>
      <tbody class="text-gray-600 divide-y bg-white">
        {% set total = 0 %}
        {% for collecteItem in collecte.collecteDetaillespeas %}
          <tr>
            <td class="px-4 py-2 text-ellipsis overflow-hidden">{{ collecteItem.pea }} Kg</td>
            <td class="px-4 py-2 text-ellipsis overflow-hidden"></td>
            <td class="px-4 py-2 whitespace-wrap text-right">{{ collecteItem.clothingPea.priceMin|format_currency('XOF', locale='de') }}</td>
          </tr>
          {% set total = collecteItem.clothingPea.priceMin %}
        {% endfor %}
        <tr>
          <td class="text-center text-xs md:text-sm px-4 py-2 whitespace-wrap">Frais de sèchage et de pliage non compris.</td>
          <td class="font-bold px-4 py-4 whitespace-nowrap">Total :</td>
          <td class="px-4 py-4 whitespace-nowrap font-bold text-right">{{ total|format_currency('XOF', locale='de') }}</td>
        </tr>
      </tbody>
    </table>
  {% else %}
    <table class="w-full sm:w-full table-auto text-sm text-left">
      <thead class="bg-gray-50 text-purple-950 w-80 font-medium border-b">
        <tr>
          <th class="py-2 px-4">Pièces</th>
          <th class="py-2 px-4">Ref</th>
          <th class="py-2 px-4">P.U</th>
          <th class="py-2 px-4">Qté</th>
          <th class="py-2 px-4">P.T</th>
        </tr>
      </thead>
      <tbody class="text-gray-600 divide-y bg-white">
        {% set total = 0 %}
        {% set priceTot = 0 %}
        {% for collecteItem in collecte.collecteDetailles %}
          <tr>
            <td class="px-4 py-2 text-ellipsis overflow-hidden">{{ collecteItem.clothingType.name }}</td>
            <td class="px-4 py-2 whitespace-wrap">{{ collecteItem.reference }}</td>
            <td class="px-4 py-2 whitespace-wrap">{{ collecteItem.clothingType.price }}</td>
            <td class="px-4 py-2 whitespace-wrap">{{ collecteItem.quantity }}</td>
            <td class="px-4 py-2 whitespace-wrap">{{ collecteItem.clothingType.price * collecteItem.quantity }}</td>
            {% set priceTot = collecteItem.clothingType.price * collecteItem.quantity %}
            {% set total = total + priceTot %}
          </tr>
        {% endfor %}
        <tr>
          <td colspan="2" class="text-center text-xs md:text-sm px-4 py-2 whitespace-wrap">Les frais de collecte et de livraison sont gratuit.</td>
          <td class="font-bold px-6 py-4 whitespace-nowrap">Total :</td>
          <td class="px-6 py-4 whitespace-nowrap font-bold">{{ total|format_currency('XOF', locale='de') }}</td>
        </tr>
      </tbody>
    </table>
  {% endif %}
</div>
{% if form != null %}
  {{ form_start(form) }}

  <div class="w-full text-center mt-4">
    <h3 class="mb-5 text-lg font-medium text-purple-900 dark:text-white">Vous effecturait le payment au collecte ou à la livraison ?</h3>
    {{ form_widget(form.paymentChoice, { label_attr: { class: 'block text-sm font-medium leading-6 cursor-pointer px-3 py-2 m-2' }, error_attr: { class: 'text-red-500 text-sm font-medium' }, attr: { class: 'block w-full flex gap-4 justify-center rounded-md border-0 py-1.5 px-4 text-center text-gray-900 ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-purple-600 sm:text-sm sm:leading-6' } }) }}

    {{ form_widget(form.totale, { attr: { value: total } }) }}
  </div>

  <div class="w-full text-right mt-4">
    <a href="{{ path('collecte.edit', { id: collecte.id }) }}" class="px-3 py-2 m-1 text-sm font-medium text-center border text-purple-700 bg-gray-100 rounded-md hover:bg-gray-200 focus:ring-none focus:outline-none focus:bg-gray-300 dark:bg-gray-200 dark:hover:bg-gray-300 dark:focus:ring-none">Edit</a>
    <button type="submit" class="px-3 py-2 m-1 text-sm font-medium text-center border text-white bg-purple-700 rounded-md hover:bg-purple-800 focus:ring-none focus:outline-none focus:bg-purple-600 dark:bg-purple-600 dark:hover:bg-purple-700 dark:focus:ring-none">Continuer</button>
  </div>
  {{ form_end(form) }}
{% endif %}

templates/collecte/show.html.twig
{% extends 'fullyAuthLayout.html.twig' %}

{% if form is defined %}
  {% form_theme form 'tailwind_2_layout.html.twig' %}
{% endif %}

{% block title %}
  Collecte
{% endblock %}

{% block body %}
  <div class="customer-form items-left flex bg-white rounded-lg py-6 flex-col min-h-full lg:px-6">
    <div class="items-start flex justify-between border-b pb-6 text-gray-600">
      <div class="max-w-3xl">
        <h3 class="text-purple-800 text-xl font-semibold sm:text-2xl">Detailles de la collecte</h3>
        <p class="text-purple-950 text-sm font-medium mt-2">Les detailles de la collecte, montant de la facture la liste des pièces et les detailles sur le client.</p>
      </div>
      <div class="flex justify-center gap-4">
        <a href="{{ path('collecte.index') }}" class="inline-flex hover:underline text-purple-700 bg-gray-100 px-2 py-2 rounded-md">Retour a la liste</a>
      </div>
    </div>
    <div class="px-4 mt-5 md:px-8 w-screen-5xl mx-auto">
      <div class="flex flex-col justify-between max-w-full">{{ include('collecte/_facture.html.twig', { collecte: collecte }) }}</div>
      <div class="w-full text-right mt-4 py-1 px-1">
        {% if collecte.status != 'En attente' %} 
          <a href="https://wa.me/221{{ collecte.customer.phoneNumber }}?text=Bonjour%20!%0ALe%20code%20de%20votre%20commande%20est%20:%20{{ collecte.secret }}%0AVoici%20le%20lien%20de%20suivie%20de%20votre%20commande%20sur%20setSetal%20service%20:%20{{ url('collecte.show', { id: collecte.id }) }}]" type="button" class="text-white bg-green-600 hover:bg-green-700 focus:outline-none font-medium rounded-lg text-sm px-3 py-1.5 text-center inline-flex items-center dark:focus:ring-gray-500 dark:hover:bg-[#050708]/30 mb-2">
            <svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" class="bi bi-whatsapp w-4 h-4 me-2" viewBox="0 0 16 16">
              <path d="M13.601 2.326A7.85 7.85 0 0 0 7.994 0C3.627 0 .068 3.558.064 7.926c0 1.399.366 2.76 1.057 3.965L0 16l4.204-1.102a7.9 7.9 0 0 0 3.79.965h.004c4.368 0 7.926-3.558 7.93-7.93A7.9 7.9 0 0 0 13.6 2.326zM7.994 14.521a6.6 6.6 0 0 1-3.356-.92l-.24-.144-2.494.654.666-2.433-.156-.251a6.56 6.56 0 0 1-1.007-3.505c0-3.626 2.957-6.584 6.591-6.584a6.56 6.56 0 0 1 4.66 1.931 6.56 6.56 0 0 1 1.928 4.66c-.004 3.639-2.961 6.592-6.592 6.592m3.615-4.934c-.197-.099-1.17-.578-1.353-.646-.182-.065-.315-.099-.445.099-.133.197-.513.646-.627.775-.114.133-.232.148-.43.05-.197-.1-.836-.308-1.592-.985-.59-.525-.985-1.175-1.103-1.372-.114-.198-.011-.304.088-.403.087-.088.197-.232.296-.346.1-.114.133-.198.198-.33.065-.134.034-.248-.015-.347-.05-.099-.445-1.076-.612-1.47-.16-.389-.323-.335-.445-.34-.114-.007-.247-.007-.38-.007a.73.73 0 0 0-.529.247c-.182.198-.691.677-.691 1.654s.71 1.916.81 2.049c.098.133 1.394 2.132 3.383 2.992.47.205.84.326 1.129.418.475.152.904.129 1.246.08.38-.058 1.171-.48 1.338-.943.164-.464.164-.86.114-.943-.049-.084-.182-.133-.38-.232" />
            </svg>Envoyer au client
          </a>
          {% else %}
          <a href="{{ path('collecte.edit', { id: collecte.id, type: collecte.collecteType }) }}" class="px-3 py-2 m-1 text-sm font-medium text-center text-white bg-purple-700 rounded-lg hover:bg-purple-800 focus:ring-none focus:outline-none focus:purple-blue-300 dark:bg-purple-600 dark:hover:bg-purple-700 dark:focus:ring-none">Modifier</a>
          <a href="{{ path('collecte.confirme', { id: collecte.id }) }}" class="text-white bg-green-600 hover:bg-green-700 focus:outline-none font-medium rounded-lg text-sm px-3 py-1.5 text-center inline-flex items-center dark:focus:ring-gray-500 dark:hover:bg-[#050708]/30 mb-2">Confirmer</a>
        {% endif %}
    </div>
  </div>
{% endblock %}